---------------------------------------------------------------
--
-- FileName : LplusFactoryData.lua
-- Creator : chentap
-- Date : 2022/06/17
-- Comment : 
--
---------------------------------------------------------------
local Lplus = require "Lplus"
---@class LplusFactoryData:System.Object
---@field public prefixes table
---@field public className string
---@field public baseClass string
---@field public requires table
---@field public befores table
---@field public fields table
---@field public constructors table
---@field public finals table
---@field public statics table
---@field public overrides table
---@field public virtuals table
---@field public methods table
---@field public Commit fun():LplusFactoryData @notnull
local class = Lplus.Class("LplusFactoryData")
do
    local def = class.define
    local function emptyFun()
        return {}
    end

    ---@type table
    def.field("table").prefixes = function()
        local prefixes = {}
        local str_mod1 = "--- %s\n"
        prefixes[1] = str_mod1
        local str = "--- Generated by EmmyLua(https://github.com/EmmyLua)\n"
        str = str.."--- Generated by LplusFactory(https://github.com/chrischentopher/wLua-Lplus-Quick-Class-File)\n"
        prefixes[2] = str
        local str_mod_name = '--- Created by %s \n'
        prefixes[3] = str_mod_name
        local str_mod_date = '--- DateTime: %02d/%02d/%02d %02d:%02d\n'
        prefixes[4] = str_mod_date
        return prefixes
    end --描述,作者

    ---@type string
    def.field("string").className = '' --类名

    ---@type string
    def.field("string").baseClass = '' --基类

    ---@type table
    def.field("table").requires = function()
        local requires = {}
        requires[#requires + 1] = string.format("local Lplus = require \"Lplus\"\n" )
        return requires
    end

    ---@type table
    def.field("table").befores = emptyFun

    ---@type table
    def.field("table").fields = emptyFun

    ---@type table
    def.field("table").constructors = emptyFun

    ---@type table
    def.field("table").finals = emptyFun

    ---@type table
    def.field("table").statics = emptyFun

    ---@type table
    def.field("table").overrides = emptyFun
    
    ---@type table
    def.field("table").virtuals = emptyFun

    ---@type table
    def.field("table").methods = emptyFun

    class.Commit()
end
return class
